title: Nathaniel's Portfolio
description: A personal site to learn more about me.

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
sass:
    style: compressed
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled:     true
  collections: true