theme: jekyll-theme-tactile
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
sass:
    style: compressed
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true